name: hamdars
description: "Test Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  Internet
  dio: ^5.6.0
  connectivity: ^3.0.6

  #  Image
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7

  #  ِDatabase
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2

  #  State Management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  equatable: ^2.0.5

  #  View
  persian_datetime_picker:
    path: packages/persian_datetime_picker/
  #  persian_datetime_picker: ^2.7.0
  persian_number_utility: ^1.1.4
  animated_toggle_switch: ^0.8.3
  context_menus: ^2.0.0+1
  webview_universal: ^0.0.5
  skeletons: ^0.0.3
  curved_carousel: ^0.0.8
  carousel_slider: ^5.0.0

  #  Utils
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  url_strategy: ^0.3.0
  get_it: ^7.7.0
  url_launcher: ^6.3.0

  #  Hot Push
  shorebird_code_push: ^1.1.4

#  Test
  flutter_gherkin: ^2.0.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  #  Generators
  build_runner: ^2.4.12
  objectbox_generator: ^4.0.2

  #  Tests
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

objectbox:
  output_dir: data/objectbox/generated

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/svg/
    - shorebird.yaml

  fonts:
    - family: openSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
        - asset: assets/fonts/opensans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/opensans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/opensans/OpenSans-Italic.ttf
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
        - asset: assets/fonts/opensans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/opensans/OpenSans-Medium.ttf
        - asset: assets/fonts/opensans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/opensans/OpenSans-SemiBoldItalic.ttf
    - family: iranyekan
      fonts:
        - asset: assets/fonts/iranyekan/IRANYekanMobileBlack.ttf
        - asset: assets/fonts/iranyekan/IRANYekanMobileBold.ttf
        - asset: assets/fonts/iranyekan/IRANYekanMobileExtraBlack.ttf
        - asset: assets/fonts/iranyekan/IRANYekanMobileExtraBold.ttf
        - asset: assets/fonts/iranyekan/IRANYekanMobileLight.ttf
        - asset: assets/fonts/iranyekan/IRANYekanMobileMedium.ttf
        - asset: assets/fonts/iranyekan/IRANYekanMobileRegular.ttf
        - asset: assets/fonts/iranyekan/IRANYekanMobileThin.ttf

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: fa # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

#  localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
#    project_id: # Configured manually or through 'Connect to Localizely' command. Get it from the https://app.localizely.com/projects page.
#    branch: # Configured manually. Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
#    upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
#    upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
#    upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
#    upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
#    upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
#    download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
#    download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
#    download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
#    ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false
